title: Andrea Cardaci
description: Personal website
url: https://cardaci.xyz

author:
  name: Andrea Cardaci
  email: cyrus.and@gmail.com
  twitter: cyrus_and

permalink: pretty

defaults:
  - values:
      layout: post

exclude:
  - /Gemfile
  - /Makefile
  - /README.md
  - /CNAME

kramdown:
  parse_block_html: true

plugins:
  - jekyll-feed
